name: AJDust
main: net.ajgaming.ajdust.Main
version: 1.0
commands:
    givedust:
        description: Gives commander selected dust.
        
permissions:
    skyblock.givedust:
        description: Gives commander dust.
        default: op